"""Generate the parameter table in docs/guide/parameters.md.

One row per parameter, straight out of the params.yaml files via model/config.py:

    parameter_name   dotted config path — the string you grep for and read as cfg.<path>
    file_name        the params.yaml it is declared in
    parameter_type   its provenance tag (the `status:` field), from the fixed vocabulary

The table sits between two HTML markers so the prose around it is never touched.
Adding a parameter to a params.yaml is all it takes to add a row.

    .venv/bin/python param_table.py            # rewrite the table
    .venv/bin/python param_table.py --check    # exit 1 if it is stale (CI / pre-commit)
"""

import os
import sys

from model.config import cfg

DOC = os.path.join("docs", "guide", "parameters.md")
BEGIN = "<!-- BEGIN PARAM TABLE — generated by param_table.py, do not edit by hand -->"
END = "<!-- END PARAM TABLE -->"

BLURB = (
    "Generated from the `params.yaml` files — regenerate with "
    "`.venv/bin/python param_table.py` after changing any of them. "
    "`parameter_type` is the entry's `status:` provenance tag."
)


def table():
    rows = ["| parameter_name | file_name | parameter_type |", "|---|---|---|"]
    for path, entry in sorted(cfg.params().items()):
        rows.append(f"| `{path}` | `{entry['file']}` | {cfg.tag_of(path)} |")
    return "\n".join(rows)


def block():
    return "\n".join([BEGIN, "", BLURB, "", table(), "", END])


def current(text):
    """The existing generated block, or None if the doc has no markers."""
    i = text.find(BEGIN)
    j = text.find(END)
    if i == -1 or j == -1:
        return None
    return text[i:j + len(END)]


def main():
    check = "--check" in sys.argv[1:]
    text = open(DOC, encoding="utf-8").read() if os.path.exists(DOC) else ""
    want = block()
    have = current(text)

    if have == want:
        print(f"{DOC}: parameter table up to date ({len(cfg.params())} parameters)")
        return 0

    if check:
        n_doc = have.count("\n| `") if have else 0
        print(f"{DOC}: parameter table is STALE "
              f"({n_doc} rows in the doc, {len(cfg.params())} parameters in the "
              f"params.yaml files, or a value/provenance moved).\n"
              f"  fix: .venv/bin/python param_table.py", file=sys.stderr)
        return 1

    if have is None:
        new = text.rstrip("\n") + ("\n\n" if text.strip() else "") + want + "\n"
    else:
        new = text.replace(have, want)
    os.makedirs(os.path.dirname(DOC), exist_ok=True)
    with open(DOC, "w", encoding="utf-8") as fh:
        fh.write(new)
    print(f"wrote {DOC} ({len(cfg.params())} parameters)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
